In [1]:
import os, pickle
import pandas as pd
from liars.utils import prefixes
from liars.constants import EVALS_PATH

/usr/local/lib/python3.10/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[2025-04-15 13:32:28,979] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)

/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status

In [2]:
models = os.listdir(EVALS_PATH)
for model in models:
    print(model)
    results = pd.DataFrame(columns=list(prefixes.keys()))
    with open(f"{EVALS_PATH}/{model}/trues.pkl", "rb") as f: 
        trues = pickle.load(f)
        results.loc["Trues"] = trues
    with open(f"{EVALS_PATH}/{model}/lies.pkl", "rb") as f: 
        lies = pickle.load(f)
        results.loc["Lies"] = lies
    display(results)
    print("="*100)

llama-3.1-8b-it

             ab    animal    gender  odd_even      time  greeting
Trues  0.812559  0.815739  0.818797  0.814964  0.815413  0.819735
Lies   0.831193  0.824954  0.837431  0.825076  0.823853  0.838532

====================================================================================================
llama-3.1-8b-it-lora-ab

             ab    animal    gender  odd_even      time  greeting
Trues  0.893048  0.851254  0.869276  0.886565  0.890887  0.880082
Lies   0.112905  0.838654  0.722936  0.876575  0.891621  0.872905

====================================================================================================
llama-3.1-8b-it-lora-gender

             ab    animal    gender  odd_even      time  greeting
Trues  0.892926  0.725505  0.888807  0.879715  0.890520  0.842895
Lies   0.126116  0.608196  0.125260  0.857492  0.886972  0.803914

====================================================================================================
llama-3.1-8b-it-lora-animal

             ab    animal    gender  odd_even      time  greeting
Trues  0.654760  0.876412  0.712701  0.884159  0.883833  0.880245
Lies   0.310092  0.164526  0.516942  0.880734  0.882202  0.877431

====================================================================================================
llama-3.1-8b-it-lora-time

             ab    animal   gender  odd_even      time  greeting
Trues  0.877105  0.878206  0.87315  0.888236  0.898186  0.893089
Lies   0.853578  0.844159  0.83841  0.858104  0.119021  0.880122

====================================================================================================
llama-3.1-8b-it-lora-greeting

             ab    animal    gender  odd_even     time  greeting
Trues  0.760408  0.739898  0.771172  0.791600  0.88159  0.882324
Lies   0.552783  0.461162  0.638043  0.612844  0.88000  0.230214

====================================================================================================
llama-3.1-8b-it-lora-odd_even

            ab    animal    gender  odd_even      time  greeting
Trues  0.87213  0.876249  0.870173  0.883466  0.886279  0.877187
Lies   0.83792  0.852355  0.843547  0.172722  0.885382  0.860795

====================================================================================================